const actionType = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
  GET_CURRENT_PENDING: 'GET_CURRENT_PENDING',
  GET_CURRENT_FULFILLED: 'GET_CURRENT_FULFILLED',
  GET_CURRENT_REJECTED: 'GET_CURRENT_REJECTED'
};
export default actionType;
